[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.1"
dashmap = "6.1.0"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
